name 'glassfish'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures glassfish'
long_description 'Installs/Configures glassfish'
version '0.1.0'
