name 'hello-world'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures hello-world'
long_description 'Installs/Configures hello-world'
version '0.1.0'
