name 'chef-learning'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-learning'
long_description 'Installs/Configures chef-learning'
version '0.1.0'
